/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectpl;

/**
 *
 * @author rainamra
 */
public class AdminFirstPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminFirstPage
     */
    public AdminFirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAdminFirstPage = new javax.swing.JPanel();
        merchButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        logOutButton = new java.awt.Button();
        UserListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAdminFirstPage.setBackground(new java.awt.Color(173, 211, 225));
        jPanelAdminFirstPage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(238, 130, 69)));

        merchButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        merchButton.setText("Merchandise");
        merchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merchButtonActionPerformed(evt);
            }
        });

        salesButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        salesButton.setText("Sales");
        salesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButtonActionPerformed(evt);
            }
        });

        createUserButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        createUserButton.setText("Create User");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        logOutButton.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        logOutButton.setLabel("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        UserListButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        UserListButton.setText("User List");
        UserListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminFirstPageLayout = new javax.swing.GroupLayout(jPanelAdminFirstPage);
        jPanelAdminFirstPage.setLayout(jPanelAdminFirstPageLayout);
        jPanelAdminFirstPageLayout.setHorizontalGroup(
            jPanelAdminFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminFirstPageLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanelAdminFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(UserListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
            .addGroup(jPanelAdminFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAdminFirstPageLayout.createSequentialGroup()
                    .addGroup(jPanelAdminFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAdminFirstPageLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelAdminFirstPageLayout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(merchButton)))
                    .addContainerGap(103, Short.MAX_VALUE)))
        );
        jPanelAdminFirstPageLayout.setVerticalGroup(
            jPanelAdminFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminFirstPageLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(salesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanelAdminFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAdminFirstPageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(merchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdminFirstPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdminFirstPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButtonActionPerformed
        dispose();
        salesInvoice sales = new salesInvoice();
        sales.setLocationRelativeTo(null);
        sales.setVisible(true);
    }//GEN-LAST:event_salesButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        dispose();
        newUser createUser = new newUser();
        createUser.setLocationRelativeTo(null);
        createUser.setVisible(true);
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void merchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merchButtonActionPerformed
        dispose();
        merchandisePage merch = new merchandisePage();
        merch.setLocationRelativeTo(null);
        merch.setVisible(true);
    }//GEN-LAST:event_merchButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        dispose();
        WelcomePage switchForm = new WelcomePage();
        switchForm.setLocationRelativeTo(null);
        switchForm.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void UserListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserListButtonActionPerformed
        dispose();
        userList userList = new userList();
        userList.setLocationRelativeTo(null);
        userList.setVisible(true);
    }//GEN-LAST:event_UserListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserListButton;
    private javax.swing.JButton createUserButton;
    private javax.swing.JPanel jPanelAdminFirstPage;
    private java.awt.Button logOutButton;
    private javax.swing.JButton merchButton;
    private javax.swing.JButton salesButton;
    // End of variables declaration//GEN-END:variables
}
