/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectpl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rainamra
 */
public class AdminLoginPage extends javax.swing.JFrame implements otherMethods {
    //To connect the project with the database
    Connection con = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    String  databaseURL = "jdbc:mysql://localhost:3306/user_details?"
            + "zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC ";
    Statement stat = null;
    
    /**
     * Creates new form AdminLoginPage
     */
    public AdminLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAdminLogin = new javax.swing.JPanel();
        adminPageLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        adminNameTF = new javax.swing.JTextField();
        adminPassPF = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        backButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAdminLogin.setBackground(new java.awt.Color(173, 211, 225));
        jPanelAdminLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(238, 130, 69)));

        adminPageLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        adminPageLabel.setText("Admin Login");
        adminPageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        usernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        usernameLabel.setText("Username:");

        passLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        passLabel.setText("Password:");

        adminNameTF.setFont(new java.awt.Font("Telugu MN", 0, 12)); // NOI18N
        adminNameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        adminNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTFActionPerformed(evt);
            }
        });

        adminPassPF.setFont(new java.awt.Font("Telugu MN", 0, 12)); // NOI18N

        loginButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.setToolTipText("");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        backButton.setLabel("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminLoginLayout = new javax.swing.GroupLayout(jPanelAdminLogin);
        jPanelAdminLogin.setLayout(jPanelAdminLoginLayout);
        jPanelAdminLoginLayout.setHorizontalGroup(
            jPanelAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminLoginLayout.createSequentialGroup()
                        .addComponent(passLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminLoginLayout.createSequentialGroup()
                        .addGroup(jPanelAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAdminLoginLayout.createSequentialGroup()
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAdminLoginLayout.createSequentialGroup()
                                .addComponent(adminPageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(adminNameTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAdminLoginLayout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(adminPassPF))
                        .addGap(30, 30, 30))))
        );
        jPanelAdminLoginLayout.setVerticalGroup(
            jPanelAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLoginLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminPageLabel)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPassPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanelAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(resetButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Overriding code since this class implements an interface
    //Display a dialog box
    @Override
    public void infoMessage(String message, String tittle)
    {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }
    //Clear the textFields
    @Override
    public void clearFieldValue() {
        adminNameTF.setText(null);
        adminPassPF.setText(null);
    }
    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        String username = adminNameTF.getText();
        String password = adminPassPF.getText();   
        
        //Check if the admin is already registered
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(databaseURL, "root", "rain2904");
            String selectQuery = "select * from admin where username= '"+username+"' "
                    + "and password= '"+password+"'";
            stat = con.createStatement();
            rs = stat.executeQuery(selectQuery);
            if(rs.next())
            {
                dispose();
                AdminFirstPage oap = new AdminFirstPage();
                oap.setLocationRelativeTo(null);
                oap.setVisible(true);
            }
            
            else
            {
                infoMessage("Admin not registered, please try again.", "Go Back!");              
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        } 
    }//GEN-LAST:event_loginButtonActionPerformed

    private void adminNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTFActionPerformed
    }//GEN-LAST:event_adminNameTFActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        clearFieldValue();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        WelcomePage backToWelcomeP = new WelcomePage();
        backToWelcomeP.setLocationRelativeTo(null);
        backToWelcomeP.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminNameTF;
    private javax.swing.JLabel adminPageLabel;
    private javax.swing.JPasswordField adminPassPF;
    private java.awt.Button backButton;
    private javax.swing.JPanel jPanelAdminLogin;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
